apiVersion: v1
kind: Service
metadata:
  name: collabora
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: collabora
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
