apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/part-of: collabora

resources:
- collabora-deployment.yaml
- collabora-service.yaml

images:
- name: docker.io/collabora/code
  newTag: 26.04.3.2.1
- name: docker.io/alpine/openssl
  newTag: "3.5.8"
