apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    app.kubernetes.io/name: collabora
  includeSelectors: true

images:
- name: collabora/code
  newTag: 24.04.13.2.1

resources:
- deployment.yaml
- service.yaml
