apiVersion: batch/v1
kind: CronJob
metadata:
  name: ddclient
spec:
  concurrencyPolicy: Forbid
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            # ddclient user is 994
            fsGroup: 994
          restartPolicy: Never
          containers:
          - image: ghcr.io/lentzi90/ddclient:master@sha256:47ac5939d879823a6c57b291623f6d70d6a1e9fa99ce6e371a41f1a32eb76555
            name: ddclient
            resources: {}
            volumeMounts:
              - name: ddclient-config
                mountPath: /ddclient/config/
                readOnly: true
          volumes:
            - name: ddclient-config
              secret:
                secretName: ddclient-config
                # Note: This does not work since it is impossible to set the owner
                # to any other user than root. Instead, kubernetes makes the volume
                # readable by the fsGroup.
                # This results in a warning from ddclient.
                defaultMode: 0600
