apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ddclient
labels:
- pairs:
    environment: turing-talos
resources:
- namespace.yaml
- ../../../ddclient/base
- externalsecret.yaml

images:
- name: lennartj/ddclient
  newTag: v2-hetzner
