apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: collabora-admin
spec:
  refreshInterval: 1h
  secretStoreRef:
    # This name must match the metadata.name in the `SecretStore`
    name: bitwarden-personal-cloud
    kind: ClusterSecretStore
  data:
  - secretKey: username
    remoteRef:
      key: 4c24a214-2277-4ee1-8f62-b4c800fe8674
  - secretKey: password
    remoteRef:
      key: 247f3c32-9cd8-459d-9c14-b4c800fe3f07
