apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opencloud

labels:
- pairs:
    environment: turing-talos

resources:
- ../../../collabora/base
- collabora-httproute.yaml
- external-secret.yaml

patches:
- path: deployment-patch.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: collabora-env
  envs:
  - collabora.env
