apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ddclient
labels:
- includeSelectors: true
  pairs:
    environment: kind

resources:
- namespace.yaml
- ../../base

secretGenerator:
- name: ddclient-config
  files:
  - ddclient.conf

images:
- name: lennartj/ddclient
  newTag: v2-hetzner
