apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opencloud

labels:
- includeSelectors: true
  pairs:
    environment: kind

resources:
- ../../base
- collabora-httproute.yaml
- wopiserver-httproute.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: collabora-env
  envs:
  - collabora.env
- name: collaboration-env
  envs:
  - collaboration.env
