name: Pipeline

on:
  pull_request:
    branches:
    - main

jobs:
  kustomize-build:
    uses: ./.github/workflows/kustomize-reusable.yaml
    with:
      paths: >
        apps/kind argocd/overlays/kind cert-manager/overlays/kind cloudnative-pg/overlays/kind external-secrets/overlays/kind hetzner-cloud-webhook/overlays/kind keycloak-operator/overlays/kind keycloak/overlays/kind jellyfin/overlays/kind metallb/overlays/kind pi-hole/overlays/kind wireguard/overlays/kind opencloud/overlays/kind
  kind-deploy:
    needs: kustomize-build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
    - name: Install Chainsaw
      uses: kyverno/action-install-chainsaw@v0.2.15
    - name: Create Kind Cluster
      uses: helm/kind-action@v1.14.0
      with:
        config: kind-config.yaml

    - name: Chainsaw test
      run: chainsaw test
      env:
        BITWARDEN_ACCESS_TOKEN: ${{ secrets.BITWARDEN_ACCESS_TOKEN }}
        TARGET_REVISION: ${{ github.head_ref }}
